# Generated by Django 4.0.4 on 2022-05-23 13:20
#custom migration
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField())
            ]
        )
    ]
