# Generated by Django 4.0.4 on 2022-05-23 13:25
# custom migration
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO api_testmodel (title,description) VALUES ('Hello!', 'This is my description');")
    ]
