# Generated by Django 4.0.4 on 2022-05-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220523_1525'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TABLE test_sql_table (column_id int, title varchar(255), description varchar(255));"
        )
    ]
