# Generated by Django 4.0.4 on 2022-05-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_third_custom_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='description_type',
            field=models.CharField(choices=[(1, 'open'), (2, 'closed')], default=1, max_length=15))
    ]
