# Generated by Django 4.0.4 on 2022-05-05 13:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('client_country', models.CharField(blank=True, max_length=25, null=True)),
                ('client_city', models.CharField(blank=True, max_length=30, null=True)),
                ('date_create_client', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company_country', models.CharField(blank=True, max_length=25, null=True)),
                ('company_city', models.CharField(blank=True, max_length=30, null=True)),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('date_create_company', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[(1, 'open'), (2, 'in_process'), (3, 'closed')], default='open', max_length=30)),
                ('square_in_meters', models.IntegerField()),
                ('date_create_order', models.DateTimeField(auto_now_add=True)),
                ('client_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clientuser')),
                ('companies', models.ManyToManyField(related_name='possible_companies', to='main.companyuser')),
            ],
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_create_review', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('rating_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.companyuser')),
                ('review_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clientuser')),
            ],
        ),
        migrations.CreateModel(
            name='RatingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create_rating', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.companyuser')),
                ('rating_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clientuser')),
                ('star_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ratingstar')),
            ],
        ),
    ]
